name: django

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
      fail-fast: false
    steps:
    - uses: actions/checkout@11bd71907b3cbb0e7e38b2117fdf7be6b3e7d24e # v4.2.2
    - name: set-up-python-${{ matrix.python-version }}
      uses: actions/setup-python@65d7e83e681a93c41b2e8dbb5d5e3cf03e07c0c1 # v5.1.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: install-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
  
  sonar:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
      fail-fast: false
    steps:
    - uses: actions/checkout@11bd71907b3cbb0e7e38b2117fdf7be6b3e7d24e # v4.2.2
    - name: sonar-scan
      uses: SonarSource/sonarqube-scan-action@689fb39b34b9aa95ebc5f8f119343ddd51542402 # v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_SCANNER_OPTS: -Dsonar.qualitygate.wait=true
      with:
        args: >
          -Dsonar.projectKey=django
          -Dsonar.organization=abhinavmedikonda
    - name: sonarQube-quality-gate-check
      id: qualitygate
      uses: SonarSource/sonarqube-quality-gate-action@923dcf4f7fcd3c2ef1dc201c10a03e2298e12c4b # latest master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
