name: django
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
      fail-fast: false
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    - name: set-up-python-${{ matrix.python-version }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
      with:
        python-version: ${{ matrix.python-version }}
    - name: install-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run-tests
      run: |
        coverage run manage.py test
        coverage xml
    # Save coverage report so next job can access it
    - name: upload-coverage-report
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
      with:
        name: coverage-${{ matrix.python-version }}
        path: coverage.xml
  
  sonar:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    # Download specific uploaded artifict
    - name: download-coverage-report
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
      with:
        name: coverage-3.9
    - name: sonar-scan
      uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=django
          -Dsonar.organization=abhinavmedikonda
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.qualitygate.wait=false
    - name: sonar-quality-gate
      id: qualitygate
      uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io

  dast:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    permissions:
      contents: read
      issues: write
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: build-docker-image
        run: docker build -t django-app .
      - name: run-django-app
        run: docker run -d -p 8000:8000 django-app
      - name: run-owasp-zap-baseline-scan
        uses: zaproxy/action-baseline@de8ad967d3548d44ef623df22cf95c3b0baf8b25
        with:
          target: "http://localhost:8000"
          fail_action: false  # don’t fail pipeline on minor issues
          rules_file_name: ".zap-rules.tsv"
          cmd_options: "-a"
      - name: upload-zap-report
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: zap-report
          path: report_html.html
      - name: upload-docker-image
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: docker-image
          path: django-app

  docker:
    runs-on: ubuntu-latest
    needs: [sonar, dast]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: docker-login
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: download-image-artifact
        uses: actions/download-artifact@v4
        with:
          name: django-app
          path: .
      - name: load-docker-image
        run: docker load -i django-app
      - name: tag-image-for-ghcr
        run: docker tag django-app ghcr.io/${{ github.repository }}:latest
      - name: push-image-to-ghcr
        run: docker push ghcr.io/${{ github.repository }}:latest
